# Generated by Django 4.2.2 on 2023-11-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_testimonial_alter_emp_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='Testimonial',
            field=models.TextField(default='agadkkkkkk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(default='gael', upload_to='testimonials/'),
            preserve_default=False,
        ),
    ]
