# Generated by Django 4.2.2 on 2023-12-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_emp_address_alter_emp_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.TextField(max_length=200)),
            ],
        ),
    ]
